package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// 1. LIGHT THEME (Clean white & slate laboratory)
val LabLightPrimary = Color(0xFF0284C7)
val LabLightOnPrimary = Color(0xFFFFFFFF)
val LabLightPrimaryContainer = Color(0xFFE0F2FE)
val LabLightOnPrimaryContainer = Color(0xFF0369A1)
val LabLightSecondary = Color(0xFF0D9488)
val LabLightOnSecondary = Color(0xFFFFFFFF)
val LabLightBackground = Color(0xFFF8FAFC)
val LabLightOnBackground = Color(0xFF0F172A)
val LabLightSurface = Color(0xFFFFFFFF)
val LabLightOnSurface = Color(0xFF0F172A)
val LabLightSurfaceVariant = Color(0xFFF1F5F9)
val LabLightOnSurfaceVariant = Color(0xFF475569)
val LabLightOutline = Color(0xFFCBD5E1)

// 2. DARK THEME (Deep charcoal & cyan/neon reactive highlights)
val LabDarkPrimary = Color(0xFF38BDF8)
val LabDarkOnPrimary = Color(0xFF082F49)
val LabDarkPrimaryContainer = Color(0xFF0C4A6E)
val LabDarkOnPrimaryContainer = Color(0xFFBAE6FD)
val LabDarkSecondary = Color(0xFF34D399)
val LabDarkOnSecondary = Color(0xFF064E3B)
val LabDarkBackground = Color(0xFF0B0F19)
val LabDarkOnBackground = Color(0xFFF8FAFC)
val LabDarkSurface = Color(0xFF151D2E)
val LabDarkOnSurface = Color(0xFFF1F5F9)
val LabDarkSurfaceVariant = Color(0xFF1E293B)
val LabDarkOnSurfaceVariant = Color(0xFF94A3B8)
val LabDarkOutline = Color(0xFF334155)

// 3. CREAM THEME (Soft parchment & warm neutral tones)
val LabCreamPrimary = Color(0xFF92400E)
val LabCreamOnPrimary = Color(0xFFFFFFFF)
val LabCreamPrimaryContainer = Color(0xFFFEF3C7)
val LabCreamOnPrimaryContainer = Color(0xFF78350F)
val LabCreamSecondary = Color(0xFFB45309)
val LabCreamOnSecondary = Color(0xFFFFFFFF)
val LabCreamBackground = Color(0xFFFDFBF7)
val LabCreamOnBackground = Color(0xFF292524)
val LabCreamSurface = Color(0xFFF6F1EA)
val LabCreamOnSurface = Color(0xFF292524)
val LabCreamSurfaceVariant = Color(0xFFEDE5D8)
val LabCreamOnSurfaceVariant = Color(0xFF57534E)
val LabCreamOutline = Color(0xFFD6CEBE)

// 4. AMBER THEME (Retro glass-and-amber dark theme)
val LabAmberPrimary = Color(0xFFF59E0B)
val LabAmberOnPrimary = Color(0xFF451A03)
val LabAmberPrimaryContainer = Color(0xFF78350F)
val LabAmberOnPrimaryContainer = Color(0xFFFDE68A)
val LabAmberSecondary = Color(0xFFD97706)
val LabAmberOnSecondary = Color(0xFF451A03)
val LabAmberBackground = Color(0xFF161009)
val LabAmberOnBackground = Color(0xFFFFFBEB)
val LabAmberSurface = Color(0xFF261D15)
val LabAmberOnSurface = Color(0xFFFEF3C7)
val LabAmberSurfaceVariant = Color(0xFF38291A)
val LabAmberOnSurfaceVariant = Color(0xFFFBBF24)
val LabAmberOutline = Color(0xFF5A3E20)
